story:
  channels:
    - https://www.youtube.com/channel/UCHq8jnJywM22kIwjo8RgCIg
    - https://www.youtube.com/channel/UCO1-4foSzj6kfbrNa3KeajQ
    - https://www.youtube.com/@life4yeon
  videos:
    - https://youtu.be/S97IVwhObHg
    - https://youtu.be/GKAZ7phHVYs
    - https://youtu.be/HGJp2DJDu7Y
    - https://youtu.be/72F38GF5MT4
    - https://youtu.be/jlaebusvXwc
    - https://youtu.be/uLyCuMylOWk
    - https://youtu.be/3p0J0_V4seA
    - https://youtu.be/BzD9ZgX7b0M
    - https://youtu.be/Ze9t7VAfEc8
    - https://youtu.be/L3WCz-2kUHg
    - https://youtu.be/CpBD7dYgkJk
    - https://youtu.be/lrg7p6crYvY
    - https://youtu.be/dO9RLPETiMQ
    - https://youtu.be/snU_B3F1WxE
    - https://youtu.be/uOjNsbFvMD0
    - https://youtu.be/Y_3RRkwy4Wc
    - https://youtu.be/6PtqKq8M9lk
    - https://youtu.be/9zFsgf-kA2U
    - https://youtu.be/oBQhyGE6Nro
    - https://youtu.be/Rhpcr6eOEEw
    - https://youtu.be/O8mr5RxukRk
    - https://youtu.be/Xyulqvpq56A
    - https://youtu.be/BeIyifbW6bY
    - https://youtu.be/SfXf9Qe5QiU
    - https://youtu.be/XZWJsEd_ojI
    - https://youtu.be/MjdFU7LQ4mg
    - https://youtu.be/LtZmY5T1YBU
    - https://youtu.be/Th4nbWKADDI

health:
  channels:
    - https://www.youtube.com/@%EB%B0%B1%EC%84%B8%EC%B9%9C%EA%B5%AC
    - https://www.youtube.com/@Dr.Dylan%EC%9D%98%EA%B1%B4%EA%B0%95%EB%B9%84%EA%B2%B0
  videos:
    - https://youtu.be/jzmttkU8qWc
    - https://youtu.be/kebVLCyfbCc
    - https://youtu.be/y0JxZJBN6hA
    - https://youtu.be/5w_MqHQ5ZSY
    - https://youtu.be/d7m02JrQIvg
    - https://youtu.be/IAzXacRI2QQ
    - https://youtu.be/IQls6svZnko
    - https://youtu.be/QUtfsZjUWYs
    - https://youtu.be/ql4_0WMYBA0
    - https://youtu.be/G3MbkJP6wb8
    - https://youtu.be/xOPsF7FB6OA
    - https://youtu.be/aM20gc2GYBw
    - https://youtu.be/RMLguUj9eBw
    - https://youtu.be/L4GW7-NrHn8
    - https://youtu.be/EFZeaOcgUxk
    - https://youtu.be/F1lj8CApngI
    - https://youtu.be/3hhhEzdp7rM
    - https://youtu.be/IHk741NCKQM
    - https://youtu.be/KsK5qZebZJI
    - https://youtu.be/6Pv4VnKABnA
    - https://youtu.be/o49mw0pQC_Y
    - https://youtu.be/_jqxjKB0Ny4
    - https://youtu.be/HQIHOpOILYY
    - https://youtu.be/r9r92SDC1M4
    - https://youtu.be/LfJt49Hqb3Q
    - https://youtu.be/SWYlxcmkZpM
    - https://youtu.be/6Cjfn-iSKxk
    - https://youtu.be/pbNGl1LeOEo
    - https://youtu.be/M30B0kSX8-8
    - https://youtu.be/EZGtI7mY9g0
    - https://youtu.be/t0lg1NHuxLo
    - https://youtu.be/Gjngum0MOTA
    - https://youtu.be/NSNZt6fvu9Q
    - https://youtu.be/5vLu7M2g8Cc

nk:
  channels: []   # 내일 알려주실 1곳을 여기에 추가
  videos: []
