story:
  must_phrases:
    - 오디오북
    - 라디오사연
    - 노후사연
    - 반전사연
    - 감동사연
    - 황혼
    - 황혼연애
    - 황혼재혼
    - 부모자식갈등
    - 상속
    - 유언
    - 고부갈등

  include:
    - 무시
    - 복수
    - 뒤집
    - 반전
    - 예비며느리
    - 가족
    - 효도
    - 재혼
    - 황혼이혼
    - 형제
    - 돈
    - 빚
    - 유산
    - 사연이야기
    - 눈물

  exclude:
    - 뉴스
    - 속보
    - 브리핑
    - 외신
    - 국뽕
    - 해외반응
    - 정치
    - 군사
    - 전투
    - 하이에나
    - 전쟁
    - 미사일
    - 사건반장
    - YTN
    - JTBC
    - MBC
    - SBS
    - 연합뉴스
    - 하이라이트
    - 쇼츠
    - shorts
    - live
    - 라이브
