story:
  include:
    - 뒤집어버렸습니다
    - 충격적입니다
    - 복수했습니다
    - 무시
    - 동창
    - 동창회
    - 상상도못했습니다
    - 예비며느리
    - 사위
    - 오열했습니다
    - 황혼
    - 재벌
    - 가난
    - 청소부
    - 할머니
    - 백만장자
    - 대기업회장
    - 시골출신
    - 사연
    - 반전
    - 고부
    - 유산
    - 눈물
    - 배신
    - 용서
  exclude:
    - 쇼츠
    - shorts
    - 라이브
    - LIVE

health:
  include:
    - 혈당
    - 당뇨
    - 콜레스테롤
    - 고혈압
    - 수면
    - 불면
    - 단백질
    - 근력
    - 근감소증
    - 관절
    - 허리
    - 무릎
    - 치매
    - 면역
    - 비타민D
    - 오메가3
    - 한방
    - 루틴
    - 식단
    - 운동
  exclude:
    - 쇼츠
    - shorts
    - 라이브
    - LIVE

nk:
  include:
    - 북한
    - 평양
    - 김정은
    - 탈북
    - 미사일
    - 제재
    - 안보
  exclude:
    - 쇼츠
    - shorts
    - 라이브
    - LIVE
