health:
  include:
    # 질환/수치
    - 혈당
    - 공복혈당
    - 당뇨
    - 콜레스테롤
    - 중성지방
    - 고혈압
    - 저혈압
    - 혈압
    - 혈관
    - 동맥경화
    - 치매
    - 파킨슨
    - 통풍
    - 지방간
    # 부위/증상
    - 관절
    - 무릎
    - 허리
    - 어깨
    - 목
    - 디스크
    - 손목
    - 고관절
    - 발목
    - 골다공증
    - 척추
    - 신경통
    - 방광
    - 전립선
    - 소화
    - 위염
    - 역류성식도염
    - 위
    - 장
    - 변비
    - 설사
    - 간
    - 신장
    - 피부
    - 염증
    - 부종
    - 어지럼
    - 빈혈
    - 두통
    - 이명
    # 생활/영양/행동
    - 수면
    - 불면
    - 코골이
    - 단백질
    - 근육
    - 근감소증
    - 루틴
    - 식단
    - 해독
    - 금기
    - 주의
    - 걷기
    - 스트레칭
    - 재활
    - 요가
    - 필라테스
    - 호흡
    - 체중
    - 다이어트
    - 저염
    - 저당
    - 저탄수
    # 영양소/식품
    - 비타민D
    - 오메가3
    - 마그네슘
    - 칼슘
    - 아연
    - 코엔자임Q10
    - 폴리페놀
    - 프로바이오틱스
    - 유산균
    - 식이섬유
    - 견과
    - 버섯
    - 채소
    - 과일
    - 올리브유
    - 시니어 멀티비타민
    # 한방/의료
    - 한방
    - 한의사
    - 약초
    - 탕
    - 차
    - 경혈
    - 침
    - 뜸
    - 보약
    - 체질
    - 한약
    - 첩약
    - 병원
    - 의사
    - 재활의학과
    - 정형외과
    - 물리치료
  exclude:
    # 정치/시사/국제
    - 트럼프
    - 바이든
    - 대선
    - 공화당
    - 민주당
    - 의회
    - 외교
    - 전쟁
    - 미사일
    - 국방
    - 안보
    - 총선
    - 대법원
    # 경제/금융
    - 경제
    - 환율
    - 금리
    - 주식
    - 증시
    - 코인
    - 비트코인
    - 부동산
    - 청약
    - 세금
    # 방송/뉴스 브랜드 & 포맷
    - 뉴스
    - 속보
    - 특보
    - 헤드라인
    - 브리핑
    - 인터뷰
    - 다큐
    - 사건반장
    - YTN
    - JTBC
    - MBC
    - SBS
    - TV조선
    - 채널A
    - 연합뉴스
    # 기타/형식
    - 연예
    - 스캔들
    - 가십
    - 셀럽
    - 게임
    - 브이로그
    - 챌린지
    - 쇼츠
    - shorts
    - 라이브
    - live
    - 실시간
    - 하이라이트
    - 클립

nk:
  include:
    # 핵심
    - 북한
    - 북
    - 평양
    - 김정은
    - 김여정
    - 내부
    - 장마당
    - 배급
    - 식량
    - 탈북
    - 보위부
    - 국경
    - 이동통제
    # 군사/외교
    - 미사일
    - 탄도미사일
    - 위성발사
    - 핵
    - 제재
    - 군사
    - 러북
    - 중북
    - 군사협력
    - 합동훈련
    # 분석/보도
    - 동향
    - 정세
    - 브리핑
    - 분석
    - 전문가
    - 박사
    - 해외언론
    - 보도
    - 유엔
    - 제재결의
    - CSIS
    - 38North
  exclude:
    # 투자/일반시사(북 맥락 없음)
    - 코인
    - 주식
    - 환율
    - 부동산
    - 비트코인
    - 연예
    - 가십
    # 국내정치 단독
    - 여당
    - 야당
    - 공약
    - 총선
    # 포맷/브랜드
    - 쇼츠
    - shorts
    - 라이브
    - live
    - 뉴스
    - 속보
    - 사건반장
    - 예능
    - 토크쇼
    - YTN
    - JTBC
    - MBC
    - SBS
    - 연합뉴스
    # 기타
    - 여행
    - 브이로그
    - 게임
    - 먹방
    - 리뷰

story:
  include:
    # 관계/갈등
    - 무시
    - 모욕
    - 굴욕
    - 참교육
    - 복수
    - 뒤집
    - 반전
    - 배신
    - 오열
    - 상상도못했습니다
    # 가족/혼인
    - 시어머니
    - 며느리
    - 예비며느리
    - 사위
    - 고부
    - 형제
    - 동창
    - 동창회
    - 가족
    - 효도
    - 황혼
    - 황혼이혼
    - 재혼
    # 재산/돈
    - 상속
    - 유산
    - 유언
    - 재산
    - 돈
    - 빚
    - 4억
    - 10억
    - 집
    - 아파트
    - 상가
    - 전세
    - 월세
    # 신분 반전
    - 백만장자
    - 재벌
    - 대기업회장
    - 청소부
    - 경비
    - 보안요원
    - 시골출신
    - 알고보니
    # 정서/구성
    - 사연
    - 감동
    - 눈물
    - 결말
    - 파국
    - 협박
    - 위장
    - 음모
  exclude:
    # 시사/보도 포맷
    - 뉴스
    - 속보
    - 특보
    - 브리핑
    - 인터뷰
    - 사건반장
    - YTN
    - JTBC
    - MBC
    - SBS
    - 연합뉴스
    # 정치/경제 일반 이슈
    - 트럼프
    - 바이든
    - 대선
    - 국방
    - 미사일
    - 환율
    - 주식
    - 코인
    - 비트코인
    - 부동산
    # 형식/기타
    - 쇼츠
    - shorts
    - 라이브
    - live
    - 하이라이트
    - 클립
    - 브이로그
    - 일상
    - 먹방
    - 게임
    - 예능
