story:
  # 제목/태그에 반드시 1개 이상 포함(필수)
  must_phrases:
    - 오디오북
    - 라디오사연
    - 6시내사연
    - 노후사연
    - 반전사연
    - 감동사연
    - 노년의 삶의지혜
    - 행복한 노후생활
    - 부모자식갈등
    - 사연이야기
    - 고부사연
    - 사연라디오

  # 포함 권장(없어도 통과 가능) — 랭킹·제목생성에 영향
  include:
    - 무시
    - 복수
    - 뒤집
    - 반전
    - 배신
    - 오열
    - 시어머니
    - 며느리
    - 예비며느리
    - 사위
    - 고부
    - 형제
    - 동창
    - 동창회
    - 가족
    - 효도
    - 황혼
    - 황혼이혼
    - 재혼
    - 상속
    - 유산
    - 유언
    - 재산
    - 돈
    - 빚
    - 백만장자
    - 재벌
    - 대기업회장
    - 청소부
    - 경비
    - 보안요원
    - 시골출신
    - 알고보니
    - 사연
    - 감동
    - 눈물
    - 결말
    - 파국
    - 협박
    - 위장
    - 음모
    - 충격

  # 즉시 제외
  exclude:
    - 뉴스
    - 속보
    - 특보
    - 브리핑
    - 인터뷰
    - 사건반장
    - YTN
    - JTBC
    - MBC
    - SBS
    - 연합뉴스
    - 트럼프
    - 바이든
    - 대선
    - 국방
    - 미사일
    - 환율
    - 주식
    - 코인
    - 비트코인
    - 부동산
    - 쇼츠
    - shorts
    - 라이브
    - live
    - 하이라이트
    - 클립
    - 브이로그
    - 일상
    - 먹방
    - 게임
    - 예능
