name: Weekly Senior Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 0"  # 매주 월요일 KST 08:00 (UTC 23:00 일)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies (weekly)
        run: |
          python -m pip install --upgrade pip
          pip install requests
          # reportlab은 주간 PDF를 만들지 않으므로 불필요하지만,
          # 월간 히스토리 스냅샷과의 호환을 고려해 설치해도 무방합니다.
          # pip install reportlab

      - name: Quick sanity checks (YouTube & SMTP)
        run: |
          python - << 'PY'
          import os, requests, smtplib
          key=os.getenv('YOUTUBE_API_KEY')
          assert key, 'YOUTUBE_API_KEY missing'
          url="https://www.googleapis.com/youtube/v3/search"
          params={'key':key,'part':'snippet','q':'시니어','type':'video','order':'date','maxResults':1}
          r=requests.get(url, params=params, timeout=20)
          print("YT status:", r.status_code)
          assert r.status_code==200, f"YouTube API error: {r.text[:200]}"
          host=os.getenv('SMTP_HOST'); port=int(os.getenv('SMTP_PORT','0'))
          assert host and port, 'SMTP_HOST/PORT missing'
          print("SMTP host/port present.")
          PY
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SMTP_HOST:       ${{ secrets.SMTP_HOST }}
          SMTP_PORT:       ${{ secrets.SMTP_PORT }}

      - name: Run Weekly Report
        run: python weekly_report.py
        env:
          # === Required ===
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          SMTP_HOST:       ${{ secrets.SMTP_HOST }}
          SMTP_PORT:       ${{ secrets.SMTP_PORT }}
          SMTP_USER:       ${{ secrets.SMTP_USER }}
          SMTP_PASS:       ${{ secrets.SMTP_PASS }}
          REPORT_EMAIL_TO: ${{ secrets.REPORT_EMAIL_TO }}

          # === Optional tuning ===
          RISING_SORT_MODE: "percent"         # 'percent' 또는 'delta'
          EXTRA_ARCHETYPES_JSON: ""           # 예: {"반려동물/건강":["반려견","노령견"]}
          EXTRA_KEYWORDS_JSON: ""             # 예: {"반려동물":["반려견","노령견"]}

      - uses: actions/upload-artifact@v4
        with:
          name: weekly-report-and-csv
          path: |
            data/outputs/weekly_report.md
            data/outputs/*.csv
